version: "3"
services:
    flask-app:
        build: ./flask-backend
        restart: always
        expose:
            - "8080"
        networks:
            - backnet
        
    proxy:
        build: ./proxy
        restart: always
        ports: 
            - 80:80
        networks:
            - backnet
        # depends_on:
        #     - flask-app
networks:
    backnet: